### ISSUE TITLE
a question abount two squences in identify_perfect_nano.py 

### ISSUE THREAD

**Issue by RyanYip-Kat** [Acribbs/TallyNN#4]
Hi,I want to ask a quetion abount,AAGCAGTGGTATCAACGCAGAGT and  TTTTTTTTTTTTTTTTTTTT in function m=regex.finditer(***),what are the means of them ? Are they a five-terminal primer and a three-terminal primer？Thanks!

**Comment by Acribbs** [comment]
Hi, If im not mistaken then the code you point to is just trying to locate the SMART primer: AAGCAGTGGTATCAACGCAGAGT and the polyT site of the read.

**Comment by RyanYip-Kat** [comment]
Well, if my nano sequencing isn't the same as yours, like my primer_5 and primer_3 are A and B, respectively,can I use your these code or how can I edit them 
![1625555310(1)](https://user-images.githubusercontent.com/67267063/124557509-2c89e180-de6c-11eb-8828-89057e7b8f92.png)

**Comment by Acribbs** [comment]
This code is really only possible for single-cell sequencing using dimer barcodes and UMIs (design found in our paper: https://www.nature.com/articles/s41587-021-00965-w). At the moment we are trying to make these commercially available and hope to have a solution in next 6 months or so. 

However, you may want to look at Matt Ritchie and or Waldmann groups fantastic code for Nanopore single-cell sequencing that might be more appropriate: https://github.com/LuyiTian/FLAMES and https://github.com/ucagenomix/sicelore. You would likely need to sequencing using both Illumina and Nanopore though.

**Comment by RyanYip-Kat** [comment]
OK,thanks your reply!
